PRED_LEN: 1
DATASET:
  NAME: 'HMD' # HMD, RLBench3
BASIC:
  NUM_GPU: 2
  BATCH_SIZE: 6
LOAD_MODEL: 'all'
LOSS:
  GAN:
    WEIGHT: 0.1
  GP:
    WEIGHT: 0.01
VIDEO_HOUR:
  MODE: 'pcf' # 'pc'(use past and current frame), 'pcf'(use past and current and future frame)
  INPUT_DEPTH: False
  INPUT_ROTATION: False
  INPUT_GRASP: False