MP_MODEL_NAME: 'sequence_hourglass' # hourglass, sequence_hourglass
PRED_LEN: 1
DATASET:
  NAME: 'HMD' # HMD, RLBench
BASIC:
  NUM_GPU: 1
  BATCH_SIZE: 3
LOAD_MODEL: 'all'
HOURGLASS:
  NUM_BLOCK: 2
  PRED_ROTATION: False
  PRED_GRASP: False
  INPUT_PAST: False
  INPUT_ROTATION: False
  INPUT_GRASP: False
VIDEO_HOUR:
  MODE: 'pcf'
SEQUENCE_HOUR:
  MODE: 2
LOSS:
  POSE:
    WEIGHT: 100.0