PRED_LEN: 1
DATASET:
  NAME: 'RLBench4' # HMD, RLBench
  RLBENCH:
    TASK_LIST: ['StackWine'] # PickUpCup, PutKnifeOnChoppingBoard PutRubbishInBin StackWine TakePlateOffColoredDishRack
BASIC:
  NUM_GPU: 1
  BATCH_SIZE: 1
LOAD_MODEL: 'all'
VIDEO_HOUR:
  MODE: 'pcf'
  INPUT_DEPTH: False
  INPUT_Z: True
  INPUT_ROTATION: True
  INPUT_GRASP: True
  WO_RESIDUAL: []
  ONLY_RGB_AUXILIARY: False
SEQUENCE_HOUR:
  MODE: 2