MP_MODEL_NAME: 'hourglass' # hourglass, sequence_hourglass
PRED_LEN: 1
PAST_LEN: 1
OPTIM:
  MPLR: 0.0001
DATASET:
  NAME: 'RLBench3' # HMD, RLBench
  RLBENCH:
    TASK_LIST: ['PickUpCup'] # PickUpCup PutKnifeOnChoppingBoard PutRubbishInBin StackWine TakePlateOffColoredDishRack
    # PATH4: '/home-local/tendon/dataset/RLBench4'
BASIC:
  NUM_GPU: 2
  BATCH_SIZE: 4
  WORKERS: 4
LOAD_MODEL: 'all'
HOURGLASS:
  NUM_BLOCK: 1
  NUM_DOWNSCALE: 4
  INTERMEDIATE_LOSS: True
  PRED_RGB: False
  PRED_ROTATION: True
  PRED_GRASP: True
  PRED_TRAJECTORY: False
  INPUT_PAST: True
  INPUT_ROTATION: True
  INPUT_GRASP: True
  INPUT_DEPTH: True
  INPUT_POSE: True
  INPUT_TRAJECTORY: False # trajectory map
  INPUT_VECTORMAP: False # vector map
  INPUT_TRAJECTORY_DEPTH: False # trajectory depth map
  INPUT_ROTATION_MAP: False # rotation map
  INPUT_GRASPMAP: False # grasp map
  INPUT_HISTORY: False # motion history image
VIDEO_HOUR:
  MODE: 'pcf'
  INPUT_DEPTH: True
  INPUT_Z: True
  INPUT_ROTATION: True
  INPUT_GRASP: True
  WO_RESIDUAL: []
  ONLY_RGB_AUXILIARY: False
SEQUENCE_HOUR:
  MODE: 2
LOSS:
  POSE:
    WEIGHT: 100.0
  ARGMAX:
    WEIGHT: 1.0
  ROTATION:
    WEIGHT: 10.0
  GRASP:
    WEIGHT: 10.0
  TRAJECTORY:
    WEIGHT: 10.0
