MP_MODEL_NAME: 'hourglass' # "hourglass"(train by BC) or "sequence_hourglass"(recursive prediction with video prediction model)
PRED_LEN: 1
DATASET:
  NAME: 'RLBench3' # HMD, RLBench3
  RLBENCH:
    TASK_LIST: ['PickUpCup'] # PickUpCup
BASIC:
  NUM_GPU: 1
  BATCH_SIZE: 1
LOAD_MODEL: 'all'
HOURGLASS:
  NUM_BLOCK: 2
  PRED_ROTATION: True
  PRED_GRASP: True
  PRED_TRAJECTORY: True
  INPUT_ROTATION: True
  INPUT_GRASP: True
  INPUT_DEPTH: True
VIDEO_HOUR:
  MODE: 'pcf' # 'pc'(use past and current frame), 'pcf'(use past and current and future frame)
  INPUT_DEPTH: True
  INPUT_ROTATION: True
  INPUT_GRASP: True
LOSS:
  POSE:
    WEIGHT: 100.0
  ARGMAX:
    WEIGHT: 1.0
  ROTATION:
    WEIGHT: 10.0
  GRASP:
    WEIGHT: 10.0
  TRAJECTORY:
    WEIGHT: 10.0