MP_MODEL_NAME: 'sequence_hourglass' # hourglass, sequence_hourglass
PRED_LEN: 8
PAST_LEN: 1
SKIP_LEN: 3
OPTIM:
  MPLR: 0.00001
SCHEDULER:
  STEPLR:
    STEP_SIZE: 15000
DATASET:
  NAME: 'RLBench4-sawyer' # HMD, RLBench4
  RLBENCH:
    TASK_LIST: ['ReachTarget'] # PickUpCup PutKnifeOnChoppingBoard PutRubbishInBin StackWine TakePlateOffColoredDishRack, ReachTarget, PushButton, CloseBox, PutUmbrellaInUmbrellaStand
    PATH4: '/home-local/tendon/dataset/RLBench4'
    PATH4_SAWYER: '/home-local/tendon/dataset/RLBench4-sawyer'
BASIC:
  NUM_GPU: 1
  BATCH_SIZE: 1
  WORKERS: 16
  MAX_ITER: 70000
LOAD_MODEL: 'all'
HOURGLASS:
  NUM_BLOCK: 1
  NUM_DOWNSCALE: 4
  INTERMEDIATE_LOSS: True
  PRED_RGB: False
  PRED_ROTATION: True
  PRED_GRASP: True
  PRED_TRAJECTORY: True
  INPUT_PAST: True
  INPUT_ROTATION: True
  INPUT_GRASP: True
  INPUT_DEPTH: False
  INPUT_POSE: True
  INPUT_TRAJECTORY: False # trajectory map
  INPUT_VECTORMAP: False # vector map
  INPUT_TRAJECTORY_DEPTH: False # trajectory depth map
  INPUT_ROTATION_MAP: False # rotation map
  INPUT_GRASPMAP: False # grasp map
  INPUT_HISTORY: False # motion history image
VIDEO_HOUR:
  MODE: 'pcf'
  INPUT_DEPTH: False
  INPUT_Z: True
  INPUT_ROTATION: True
  INPUT_GRASP: True
  WO_RESIDUAL: []
  ONLY_RGB_AUXILIARY: False
SEQUENCE_HOUR:
  MODE: 2
LOSS:
  POSE:
    WEIGHT: 100.0
  ARGMAX:
    WEIGHT: 1.0
  ROTATION:
    WEIGHT: 10.0
  GRASP:
    WEIGHT: 10.0
  TRAJECTORY:
    WEIGHT: 10.0
