MP_MODEL_NAME: 'sequence_hourglass' # hourglass, sequence_hourglass
PRED_LEN: 1
PAST_LEN: 5
DATASET:
  NAME: 'RLBench3' # HMD, RLBench
  RLBENCH:
    TASK_LIST: ['PickUpCup'] # PickUpCup PutKnifeOnChoppingBoard PutRubbishInBin StackWine TakePlateOffColoredDishRack
    # PATH4: '/home-local/tendon/dataset/RLBench4'
    RANDOM_LEN: 10
BASIC:
  NUM_GPU: 1
  BATCH_SIZE: 1
  WORKERS: 4
LOAD_MODEL: 'all'
HOURGLASS:
  PRED_RGB: False
  PRED_ROTATION: True
  PRED_GRASP: True
  PRED_TRAJECTORY: True
  INPUT_PAST: True
  INPUT_ROTATION: True
  INPUT_GRASP: True
  INPUT_DEPTH: True
  INPUT_POSE: True
VIDEO_HOUR:
  MODE: 'pc'
  INPUT_DEPTH: True
  INPUT_Z: True
  INPUT_ROTATION: True
  INPUT_GRASP: True
  WO_RESIDUAL: []
  ONLY_RGB_AUXILIARY: False