PRED_LEN: 1
DATASET:
  NAME: 'RLBench3' # HMD, RLBench3
  RLBENCH:
    TASK_LIST: ['PickUpCup'] # PickUpCup
BASIC:
  NUM_GPU: 1
  BATCH_SIZE: 1
LOAD_MODEL: 'all'
LOSS:
  GAN:
    WEIGHT: 0.1
  GP:
    WEIGHT: 0.01
VIDEO_HOUR:
  MODE: 'pcf'
  INPUT_DEPTH: False
  INPUT_ROTATION: True
  INPUT_GRASP: True