MP_MODEL_NAME: 'sequence_hourglass' # hourglass, sequence_hourglass
DATASET:
  NAME: 'RLBench3' # HMD, RLBench3
  RLBENCH:
    TASK_LIST: ['PickUpCup'] # PickUpCup
BASIC:
  NUM_GPU: 1
  BATCH_SIZE: 1
LOAD_MODEL: 'all'
HOURGLASS:
  NUM_BLOCK: 2
  PRED_ROTATION: True
  PRED_GRASP: True
  PRED_TRAJECTORY: False
  INPUT_PAST: True
  INPUT_ROTATION: True
  INPUT_GRASP: True
  INPUT_DEPTH: True
VIDEO_HOUR:
  MODE: 'pcf'
  INPUT_DEPTH: True
  INPUT_ROTATION: True
  INPUT_GRASP: True
SEQUENCE_HOUR:
  MODE: 2