PRED_LEN: 1
PAST_LEN: 1
SKIP_LEN: 5

DATASET:
  NAME: 'RLBench3' # HMD, RLBench
  RLBENCH:
    TASK_LIST: ['PickUpCup'] # PickUpCup, PutKnifeOnChoppingBoard PutRubbishInBin StackWine TakePlateOffColoredDishRack
    RANDOM_LEN: 2
BASIC:
  NUM_GPU: 2
  BATCH_SIZE: 4
LOAD_MODEL: 'all'
LOSS:
  GAN:
    WEIGHT: 0.1
  GP:
    WEIGHT: 0.01
VIDEO_HOUR:
  MODE: 'pcf'
  INPUT_DEPTH: False
  INPUT_Z: True
  INPUT_ROTATION: True
  INPUT_GRASP: True
  WO_RESIDUAL: []
  ONLY_RGB_AUXILIARY: True
SEQUENCE_HOUR:
  MODE: 2