PRED_LEN: 1
PAST_LEN: 1
SKIP_LEN: 3
DATASET:
  NAME: 'RLBench4-sawyer' # HMD, RLBench
  RLBENCH:
    TASK_LIST: ['TakePlateOffColoredDishRack'] # PickUpCup, PutKnifeOnChoppingBoard PutRubbishInBin PutUmbrellaInUmbrellaStand StackWine ScoopWithSpatula TakePlateOffColoredDishRack PushButton CloseBox ReachTarget，
    RANDOM_LEN: 1
    # PATH4: '/home-local/tendon/dataset/RLBench4'
BASIC:
  NUM_GPU: 1
  BATCH_SIZE: 4
  MAX_ITER: 110000
LOAD_MODEL: 'all'
LOSS:
  GAN:
    WEIGHT: 0.1
  GP:
    WEIGHT: 0.01
VIDEO_HOUR:
  MODE: 'pc'
  INPUT_DEPTH: False
  INPUT_Z: True
  INPUT_ROTATION: True
  INPUT_GRASP: True
  WO_RESIDUAL: []
  ONLY_RGB_AUXILIARY: False
SEQUENCE_HOUR:
  MODE: 2