MP_MODEL_NAME: 'hourglass' # hourglass, sequence_hourglass
PRED_LEN: 1
DATASET:
  NAME: 'RLBench' # HMD, RLBench
BASIC:
  NUM_GPU: 1
  BATCH_SIZE: 3
LOAD_MODEL: 'all'
HOURGLASS:
  NUM_BLOCK: 2
  NUM_DOWNSCALE: 4
  INTERMEDIATE_LOSS: True
  PRED_RGB: False
  PRED_ROTATION: True
  PRED_GRASP: True
  INPUT_PAST: True
  INPUT_ROTATION: True
  INPUT_GRASP: True
VIDEO_HOUR:
  MODE: 'pcf'
SEQUENCE_HOUR:
  MODE: 2
LOSS:
  POSE:
    WEIGHT: 10.0
  ARGMAX:
    WEIGHT: 1.0